export const MESSAGES = {
    DATA_FETCH_SUCCESS: "Data fetched successfully.",
    LOGIN_SUCCESS: "Login successful.",
    USER_NOT_FOUND: "User not found.",
    INVALID_CREDENTIALS: "Invalid credentials.",
    INTERNAL_SERVER_ERROR: "Internal server error.",
    LOGIN_INVALID: "Invalid user ID or password.",
    REQUIRED_FIELDS: "Please fill all required fields.",
    RESET_LINK_SENT: "A password reset link has been sent to your registered email successfully.",
    RESET_LINK_ERROR: "An error occurred while sending the password reset link.",
    PASSWORD_UPDATED: "Password updated successfully.",
    TOKEN_EXPIRED: "The token has expired. Please request a new password reset link.",
    INVALID_TOKEN: "Invalid link or expired token.",
    RESET_ERROR: "An error occurred while processing your password reset request.",
    CONTACT_SAVED: "Your contact message has been submitted successfully.",
    CONTACT_NOT_FOUND: "No contact messages found.",
    CONTACT_DELETED: "Contact deleted successfully.",
    NO_FILE_UPLOAD: "No file uploaded",
    PROFILE_UPDATED: "Profile updated successfully.",
    ACCESS_DENIED: "Access Denied. No token provided."
};
